package com.ejemplo.vaadin.admusuarios;

import com.ejemplo.vaadin.entidades.Usuario;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.validator.EmailValidator;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Form;
import com.vaadin.ui.TextField;

public class UsuarioForm extends Form {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField txtClave;
	@AutoGenerated
	private TextField txtCorreo;
	@AutoGenerated
	private TextField txtApellidos;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private Button btnInsertar;
	@AutoGenerated
	private Button btnReset;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UsuarioForm() {
				
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// btnBorrar
		btnReset= new Button();
		btnReset.setCaption("Button");
		btnReset.setImmediate(false);
		btnReset.setWidth("-1px");
		btnReset.setHeight("-1px");
		//mainLayout.addComponent(btnReset, "top:294.0px;left:210.0px;");
		
		// btnInsertar
		btnInsertar = new Button();
		btnInsertar.setCaption("Button");
		btnInsertar.setImmediate(false);
		btnInsertar.setWidth("-1px");
		btnInsertar.setHeight("-1px");
		//mainLayout.addComponent(btnInsertar, "top:294.0px;left:380.0px;");
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("-1px");
		txtNombre.setHeight("-1px");
		txtNombre.setRequired(true);
		txtNombre.setRequiredError("falta en nombre");
		//mainLayout.addComponent(txtNombre, "top:100.0px;left:40.0px;");
		
		// txtApellidos
		txtApellidos = new TextField();
		txtApellidos.setCaption("Apèllidos");
		txtApellidos.setImmediate(false);
		txtApellidos.setWidth("-1px");
		txtApellidos.setHeight("-1px");
		txtApellidos.setRequired(true);
		txtApellidos.setRequiredError("falta los apellidos");
		//mainLayout.addComponent(txtApellidos, "top:120.0px;left:276.0px;");
		
		// txtCorreo
		txtCorreo = new TextField();
		txtCorreo.setCaption("Email");
		txtCorreo.setImmediate(false);
		txtCorreo.setWidth("-1px");
		txtCorreo.setHeight("-1px");
		txtCorreo.setRequired(true);
		txtCorreo.addValidator(new EmailValidator("El email es obligatorio"));
		//mainLayout.addComponent(txtCorreo, "top:200.0px;left:60.0px;");
		
		// txtClave
		txtClave = new TextField();
		txtClave.setCaption("Clave");
		txtClave.setImmediate(false);
		txtClave.setWidth("-1px");
		txtClave.setHeight("-1px");
		txtClave.setRequired(true);
		txtClave.setRequiredError("Debes escribir la clave");
		//mainLayout.addComponent(txtClave, "top:180.0px;left:263.0px;");
		
		addField("txtNombre", txtNombre);
		addField("txtApellidos", txtApellidos);
		addField("txtCorreo", txtCorreo);
		addField("txtClave", txtClave);
		addField("btnReset", btnReset);
		addField("btnInsertar", btnInsertar);
		
		//return mainLayout;
	}
	
	public void entidadAFormulario( Usuario usuario) {
		txtNombre.setValue(usuario.getNombres());
		txtApellidos.setValue(usuario.getApellidos());
		txtCorreo.setValue(usuario.getCorreo());
		txtClave.setValue(usuario.getClave());
		
	}
	
	public Usuario formularioAEntidad() {
		Usuario user = new Usuario();
		user.setNombres(txtNombre.getValue().toString());
		user.setApellidos(txtApellidos.getValue().toString());
		user.setCorreo(txtCorreo.getValue().toString());
		user.setClave(txtClave.getValue().toString());
		
		return user;
	}

	public AbsoluteLayout getMainLayout() {
		return mainLayout;
	}

	public void setMainLayout(AbsoluteLayout mainLayout) {
		this.mainLayout = mainLayout;
	}

	public TextField getTxtClave() {
		return txtClave;
	}

	public void setTxtClave(TextField txtClave) {
		this.txtClave = txtClave;
	}

	public TextField getTxtCorreo() {
		return txtCorreo;
	}

	public void setTxtCorreo(TextField txtCorreo) {
		this.txtCorreo = txtCorreo;
	}

	public TextField getTxtApellidos() {
		return txtApellidos;
	}

	public void setTxtApellidos(TextField txtApellidos) {
		this.txtApellidos = txtApellidos;
	}

	public TextField getTxtNombre() {
		return txtNombre;
	}

	public void setTxtNombre(TextField txtNombre) {
		this.txtNombre = txtNombre;
	}

	public Button getBtnInsertar() {
		return btnInsertar;
	}

	public void setBtnInsertar(Button btnInsertar) {
		this.btnInsertar = btnInsertar;
	}

	public Button getBtnReset() {
		return btnReset;
	}

	public void setBtnReset(Button btnReset) {
		this.btnReset = btnReset;
	}

}
